# WINDOW

SCREEN_BACKGROUND_COLOR = 'black'
SCREEN_TITLE = 'SnakeGameIPX'

BORDER_COLOR = 'white'
BORDER_WIDTH = 4

GAME_BORDER_LENGHT = 800
GAME_BORDER_HEIGHT = 600

SCORE_BORDER_LENGHT = 370
SCORE_BORDER_HEIGHT = 600

BORDER_DRAWING_SPEED = 0 # MAXIMUM SPEED

INIT_GAME_BORDER_POS_X = -620
INIT_GAME_BORDER_POS_Y = -300

INIT_SCORE_BORDER_POS_X = 250
INIT_SCORE_BORDER_POS_Y = -300

# SNAKE
SNAKE_HEAD_SHAPE_UP = r'Images\snake_head_up.gif'
SNAKE_HEAD_SHAPE_DOWN = r'Images\snake_head_down.gif'
SNAKE_HEAD_SHAPE_RIGHT = r'Images\snake_head_right.gif'
SNAKE_HEAD_SHAPE_LEFT = r'Images\snake_head_left.gif'

SNAKE_BODY_SEGMENT_SHAPE = r'Images\snake_segment.gif'

INIT_SNAKE_POS_X = - 500
INIT_SNAKE_POS_Y = 0

SNAKE_FORWARD_DISTANCE = 40

# DIRECTIONS
RIGHT = 0
UP = 90
LEFT = 180
DOWN = 270